import{a as h,S as p,i as l}from"./assets/vendor-fe22c0f2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const f="live_CgFNJ52ujOJpDB32oyPIWsDLhJLkQck9ObP4pbWX6xNuFZ0SXuimVoJ674rK3QhY",g="https://api.thecatapi.com/v1",y="/breeds",S="/images/search",u=h.create({baseURL:g,headers:{"x-api-key":f}}),v=()=>u.get(y),b=t=>{const o=new URLSearchParams({breed_ids:t});return u.get(`${S}?${o}`)},w=t=>{t.classList.remove("visually-hidden")},L=t=>{t.classList.add("visually-hidden")},n={show:w,hide:L},m=document.querySelector(".breed-select"),i=document.querySelector(".loader"),d=document.querySelector(".cat-info");n.show(i);const A=t=>{const o=t.map(({id:r,name:c})=>({text:c,value:r}));o.unshift({text:"",placeholder:!0}),_.setData(o),n.hide(i),n.show(m)},T=t=>{const{url:o,breeds:[{name:r,temperament:c,description:e}]}=t;d.innerHTML=`
    <img class="cat-img" src="${o}" alt="${r}">
    <div class="cat-content">
      <div class="cat-name">${r}</div>
      <div class="cat-description">${e}</div>
      <div class="cat-temperament">Temperament: ${c}</div>
    </div>
  `,n.hide(i),n.show(d)},_=new p({select:m,settings:{placeholderText:"Select a cat"},events:{afterChange:t=>{const o=t[0].value;o&&(n.hide(d),n.show(i),b(o).then(({data:r})=>T(r[0])).catch(()=>{l.error({message:"Oops! Something went wrong! Try reloading the page!",position:"topRight"})}))}}});v().then(({data:t})=>A(t)).catch(()=>{l.error({message:"Oops! Something went wrong! Try reloading the page!",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
